apiVersion: apps/v1
kind: Deployment
metadata:
  name: article-service-deployment
  labels:
    app: article-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: article-service-pod
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: article-service-pod
    spec:
      containers:
      - name: article-service-container
        image: #####
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: ####
        envFrom:
          - configMapRef:
              name: spring-config
          - secretRef:
              name: spring-secrets
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
            readinessProbe:
              httpGet:
                path: /actuator/health
                port: 8080
              initialDelaySeconds: 30
              periodSeconds: 10
            livenessProbe:
              httpGet:
                path: /actuator/health
                port: 8080
              initialDelaySeconds: 45
              periodSeconds: 20
            imagePullSecrets:
              - name: regcred