-- insert values for document_metadata.record_state
INSERT INTO document_metadata.record_state (id, code) VALUES (gen_random_uuid(), 'DRAFT');
INSERT INTO document_metadata.record_state (id, code) VALUES (gen_random_uuid(), 'PUBLISH');
INSERT INTO document_metadata.record_state (id, code) VALUES (gen_random_uuid(), 'UN_PUBLISH');
INSERT INTO document_metadata.record_state (id, code) VALUES (gen_random_uuid(), 'REVIEW');
INSERT INTO document_metadata.record_state (id, code) VALUES (gen_random_uuid(), 'SCHEDULED_PUBLISH');
INSERT INTO document_metadata.record_state (id, code) VALUES (gen_random_uuid(), 'ARCHIVE');

-- insert values for document_metadata.record_type
INSERT INTO document_metadata.record_type (id, code) VALUES (gen_random_uuid(), 'S3_ARTICLE_CONTENT');
INSERT INTO document_metadata.record_type (id, code) VALUES (gen_random_uuid(), 'S3_ARTICLE_ASSET');
INSERT INTO document_metadata.record_type (id, code) VALUES (gen_random_uuid(), 'MP3');
INSERT INTO document_metadata.record_type (id, code) VALUES (gen_random_uuid(), 'WAV');
INSERT INTO document_metadata.record_type (id, code) VALUES (gen_random_uuid(), 'OGG');
INSERT INTO document_metadata.record_type (id, code) VALUES (gen_random_uuid(), 'MP4');
INSERT INTO document_metadata.record_type (id, code) VALUES (gen_random_uuid(), 'OGG');
INSERT INTO document_metadata.record_type (id, code) VALUES (gen_random_uuid(), 'WEBM');
INSERT INTO document_metadata.record_type (id, code) VALUES (gen_random_uuid(), 'MKV');
INSERT INTO document_metadata.record_type (id, code) VALUES (gen_random_uuid(), 'XML');
INSERT INTO document_metadata.record_type (id, code) VALUES (gen_random_uuid(), 'JSON');
INSERT INTO document_metadata.record_type (id, code) VALUES (gen_random_uuid(), 'TXT');
INSERT INTO document_metadata.record_type (id, code) VALUES (gen_random_uuid(), 'CSV');
INSERT INTO document_metadata.record_type (id, code) VALUES (gen_random_uuid(), 'XLS');
INSERT INTO document_metadata.record_type (id, code) VALUES (gen_random_uuid(), 'XLSX');
INSERT INTO document_metadata.record_type (id, code) VALUES (gen_random_uuid(), 'DOC');
INSERT INTO document_metadata.record_type (id, code) VALUES (gen_random_uuid(), 'DOCX');
INSERT INTO document_metadata.record_type (id, code) VALUES (gen_random_uuid(), 'PDF');
INSERT INTO document_metadata.record_type (id, code) VALUES (gen_random_uuid(), 'PPT');
INSERT INTO document_metadata.record_type (id, code) VALUES (gen_random_uuid(), 'PPTX');
INSERT INTO document_metadata.record_type (id, code) VALUES (gen_random_uuid(), 'ZIP');
INSERT INTO document_metadata.record_type (id, code) VALUES (gen_random_uuid(), 'GIF');
INSERT INTO document_metadata.record_type (id, code) VALUES (gen_random_uuid(), 'JPG');
INSERT INTO document_metadata.record_type (id, code) VALUES (gen_random_uuid(), 'PNG');
INSERT INTO document_metadata.record_type (id, code) VALUES (gen_random_uuid(), 'SVG');
INSERT INTO document_metadata.record_type (id, code) VALUES (gen_random_uuid(), 'HTML');
INSERT INTO document_metadata.record_type (id, code) VALUES (gen_random_uuid(), 'CSS');
INSERT INTO document_metadata.record_type (id, code) VALUES (gen_random_uuid(), 'CODE_FILE');
INSERT INTO document_metadata.record_type (id, code) VALUES (gen_random_uuid(), 'CODE_SNIPPET');
INSERT INTO document_metadata.record_type (id, code) VALUES (gen_random_uuid(), 'CODE_EDITOR');
