name: Build and Push to GitHub Packages

on:
  push:
    branches:
      - main
    # Only run on pushes to the 'main' branch

env:
  # Use this env variable to set the image name and tag
  # ghcr.io/OWNER/REPOSITORY_NAME:latest
  # We use github.repository which is automatically OWNER/REPOSITORY_NAME
  IMAGE_NAME: ghcr.io/article-service

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    # Necessary permissions for the workflow token to push to the registry
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          # The GITHUB_TOKEN is automatically provided by GitHub Actions
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          # Dynamically tag the image with 'latest' and the commit SHA
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          # Pass the credentials as build arguments, as per your Dockerfile
          build-args: |
            GITHUB_ACTOR=${{ github.actor }}
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}